# These are supported funding model platforms

patreon: "https://patreon.com/Johnnie610?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink"
ko_fi: "https://ko-fi.com/johnnie610"
