site_name: PyKeyboard Documentation
site_description: Modern, Type-Safe Keyboard Library for Kurigram
site_author: Johnnie
site_url: https://pykeyboard.readthedocs.io/

# Repository
repo_name: johnnie-610/pykeyboard
repo_url: https://github.com/johnnie-610/pykeyboard
# edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: johnnie-610/pykeyboard
      branch: main

# Customization
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/johnnie-610/pykeyboard
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pykeyboard-kurigram/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: johnnie-610
      repo: pykeyboard
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quickstart.md
  - User Guide:
      - Inline Keyboards: inline-keyboards.md
      - Reply Keyboards: reply-keyboards.md
      - Pagination: pagination.md
      - Language Selection: languages.md
      - Advanced Features: advanced.md
  - API Reference:
      - InlineKeyboard: api/inline-keyboard.md
      - ReplyKeyboard: api/reply-keyboard.md
      - Buttons: api/buttons.md
      - Builder: api/builder.md
      - Utilities: api/utilities.md
  - Examples:
      - Basic Bot: examples/basic-bot.md
      - Menu System: examples/menu-system.md
      - E-commerce Bot: examples/ecommerce.md
      - Multi-language Bot: examples/multilingual.md
  - Contributing: contributing.md
